# Copernicus Solar Forecasting — notebook 2 : métriques, baselines et premiers modèles tabulaires

Ce notebook poursuit le travail du notebook 1 en se concentrant sur :

- la mise en place de l'évaluation ;
- la construction de baselines simples mais pertinentes ;
- l'entraînement des premiers modèles supervisés classiques sur les features tabulaires ;
- la comparaison des performances sur un split chronologique train / validation.

## Objectifs
- vérifier que les métriques sont bien définies et exploitables ;
- établir une ou plusieurs **baselines de référence** ;
- tester plusieurs modèles classiques :
  - Ridge,
  - Elastic Net,
  - Random Forest,
  - HistGradientBoosting ;
- comparer les performances globales et par horizon ;
- identifier une première famille de modèles prometteuse pour la suite du projet.

## Imports et configurations

In [1]:
from __future__ import annotations

from pathlib import Path
import sys
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 120)
plt.style.use("default")
warnings.filterwarnings("ignore")

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
CANDIDATE_ROOTS = [
    Path.cwd(),
    Path.cwd().parent,
    Path("/mnt/data"),
]

PROJECT_ROOT = None
for candidate in CANDIDATE_ROOTS:
    if (candidate / "config.py").exists() or (candidate / "src").exists():
        PROJECT_ROOT = candidate
        break

if PROJECT_ROOT is None:
    PROJECT_ROOT = Path.cwd()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT_ROOT =", PROJECT_ROOT)

PROJECT_ROOT = c:\Users\alixg\OneDrive - Université Paris-Dauphine\M2 Quant\Machine Learning\projet\copernicus_solar_forecasting

In [4]:
from config import (
    FORECAST_HORIZONS_MINUTES,
    VALIDATION_FRACTION,
    INPUT_VARIABLES,
)

from src.data_loading import open_processed_profile, extract_roi
from src.features import build_physical_inputs, build_tabular_features, build_advanced_features
from src.preprocessing import (
    temporal_train_validation_split,
    fit_standardizer,
    transform_with_standardizer,
)

from src.metrics import (
    evaluate_forecasts,
    evaluate_by_horizon,
    evaluate_spatial_means,
    evaluate_model_bundle,
    compare_global_scores,
    add_skill_scores,
)

from src.baselines import (
    persistence_last_ghi_baseline,
    persistence_csi_baseline,
    mean_image_baseline,
)

from models.models_tabular import (
    flatten_target,
    prepare_tabular_inputs,
    fit_ridge_multioutput,
    fit_elasticnet_multioutput,
    fit_random_forest_multioutput,
    fit_hist_gb_multioutput,
    predict_tensor,
)

from src.visualization import plot_error_analysis

## Paramètres du notebook

In [5]:
# %% Paramètres

PROFILE_FOR_MODELING = "dev"   # mettre "sample" ou "full" plus tard
RANDOM_STATE = 42

RIDGE_ALPHA = 1.0

ELASTICNET_ALPHA = 0.001
ELASTICNET_L1_RATIO = 0.5

RF_N_ESTIMATORS = 50
RF_MAX_DEPTH = 10

HGB_MAX_DEPTH = 6
HGB_LEARNING_RATE = 0.05
HGB_MAX_ITER = 200

## 1. Chargement des données et reconstruction du pipeline

On recharge le profil processed principal puis on reconstruit les objets nécessaires :
- split train / validation chronologique ;
- représentation physique ;
- standardisation ajustée sur le train uniquement ;
- features tabulaires ;
- cibles train / validation.

In [6]:
# %% Chargement du profil train

data = open_processed_profile(PROFILE_FOR_MODELING, split="train")
print("Variables disponibles :", list(data["X"].keys()))
print("Shape target :", data["y"].shape)

Variables disponibles : ['GHI', 'CLS', 'SZA', 'SAA']
Shape target : (32, 4, 51, 51)

In [7]:
# %% Split chronologique train / validation

train_idx, val_idx = temporal_train_validation_split(
    n_samples=len(data["indices"]),
    validation_fraction=VALIDATION_FRACTION,
)

print("n_train =", len(train_idx))
print("n_val   =", len(val_idx))

n_train = 25
n_val   = 7

In [8]:
# %% Jeux bruts train / val

train_arrays_raw = {name: values[train_idx] for name, values in data["X"].items()}
val_arrays_raw = {name: values[val_idx] for name, values in data["X"].items()}

train_target = data["y"][train_idx]
val_target = data["y"][val_idx]

print("Train target :", train_target.shape)
print("Val target   :", val_target.shape)

Train target : (25, 4, 51, 51)
Val target   : (7, 4, 51, 51)

In [9]:
# %% Représentation physique

train_arrays_phys = build_physical_inputs(
    train_arrays_raw,
    keep_raw_ghi=False,
    encode_angles=True,
)

val_arrays_phys = build_physical_inputs(
    val_arrays_raw,
    keep_raw_ghi=False,
    encode_angles=True,
)

print("Variables physiques :", list(train_arrays_phys.keys()))

Variables physiques : ['CSI', 'CLS', 'SZA_sin', 'SZA_cos', 'SAA_sin', 'SAA_cos']

In [10]:
X_train_adv = build_advanced_features(train_arrays_raw)
X_val_adv = build_advanced_features(val_arrays_raw)

print(f"Nouvelle forme des features : {X_train_adv.shape}")

Nouvelle forme des features : (25, 16)

In [11]:
# %% Standardisation fit sur train seulement

standardizer = fit_standardizer(
    train_arrays_phys,
    variables=train_arrays_phys.keys(),
)

train_arrays_std = transform_with_standardizer(train_arrays_phys, standardizer)
val_arrays_std = transform_with_standardizer(val_arrays_phys, standardizer)

In [12]:
# %% Features tabulaires

tabular_features_train = build_tabular_features(train_arrays_std)
tabular_features_val = build_tabular_features(val_arrays_std)

print("Tabular train shape :", tabular_features_train.shape)
print("Tabular val shape   :", tabular_features_val.shape)

display(tabular_features_train.head())

Tabular train shape : (25, 502)
Tabular val shape   : (7, 502)

,CSI_mean_t0,CSI_std_t0,CSI_min_t0,CSI_max_t0,CSI_mean_t1,CSI_std_t1,CSI_min_t1,CSI_max_t1,CSI_mean_t2,CSI_std_t2,CSI_min_t2,CSI_max_t2,CSI_mean_t3,CSI_std_t3,CSI_min_t3,CSI_max_t3,CSI_mean_global,CSI_std_global,CSI_trend_last_minus_first,CSI_q25_t0,CSI_q50_t0,CSI_q75_t0,CSI_q25_t1,CSI_q50_t1,CSI_q75_t1,CSI_q25_t2,CSI_q50_t2,CSI_q75_t2,CSI_q25_t3,CSI_q50_t3,CSI_q75_t3,CSI_q1_mean_t0,CSI_q1_mean_t1,CSI_q1_mean_t2,CSI_q1_mean_t3,CSI_q2_mean_t0,CSI_q2_mean_t1,CSI_q2_mean_t2,CSI_q2_mean_t3,CSI_q3_mean_t0,CSI_q3_mean_t1,CSI_q3_mean_t2,CSI_q3_mean_t3,CSI_q4_mean_t0,CSI_q4_mean_t1,CSI_q4_mean_t2,CSI_q4_mean_t3,CLS_mean_t0,CLS_std_t0,CLS_min_t0,CLS_max_t0,CLS_mean_t1,CLS_std_t1,CLS_min_t1,CLS_max_t1,CLS_mean_t2,CLS_std_t2,CLS_min_t2,CLS_max_t2,CLS_mean_t3,CLS_std_t3,CLS_min_t3,CLS_max_t3,CLS_mean_t4,CLS_std_t4,CLS_min_t4,CLS_max_t4,CLS_mean_t5,CLS_std_t5,CLS_min_t5,CLS_max_t5,CLS_mean_t6,CLS_std_t6,CLS_min_t6,CLS_max_t6,CLS_mean_t7,CLS_std_t7,CLS_min_t7,CLS_max_t7,CLS_mean_global,CLS_std_global,CLS_trend_last_minus_first,CLS_q25_t0,CLS_q50_t0,CLS_q75_t0,CLS_q25_t1,CLS_q50_t1,CLS_q75_t1,CLS_q25_t2,CLS_q50_t2,CLS_q75_t2,CLS_q25_t3,CLS_q50_t3,CLS_q75_t3,CLS_q25_t4,CLS_q50_t4,CLS_q75_t4,CLS_q25_t5,CLS_q50_t5,CLS_q75_t5,...,SAA_sin_q3_mean_t7,SAA_sin_q4_mean_t0,SAA_sin_q4_mean_t1,SAA_sin_q4_mean_t2,SAA_sin_q4_mean_t3,SAA_sin_q4_mean_t4,SAA_sin_q4_mean_t5,SAA_sin_q4_mean_t6,SAA_sin_q4_mean_t7,SAA_cos_mean_t0,SAA_cos_std_t0,SAA_cos_min_t0,SAA_cos_max_t0,SAA_cos_mean_t1,SAA_cos_std_t1,SAA_cos_min_t1,SAA_cos_max_t1,SAA_cos_mean_t2,SAA_cos_std_t2,SAA_cos_min_t2,SAA_cos_max_t2,SAA_cos_mean_t3,SAA_cos_std_t3,SAA_cos_min_t3,SAA_cos_max_t3,SAA_cos_mean_t4,SAA_cos_std_t4,SAA_cos_min_t4,SAA_cos_max_t4,SAA_cos_mean_t5,SAA_cos_std_t5,SAA_cos_min_t5,SAA_cos_max_t5,SAA_cos_mean_t6,SAA_cos_std_t6,SAA_cos_min_t6,SAA_cos_max_t6,SAA_cos_mean_t7,SAA_cos_std_t7,SAA_cos_min_t7,SAA_cos_max_t7,SAA_cos_mean_global,SAA_cos_std_global,SAA_cos_trend_last_minus_first,SAA_cos_q25_t0,SAA_cos_q50_t0,SAA_cos_q75_t0,SAA_cos_q25_t1,SAA_cos_q50_t1,SAA_cos_q75_t1,SAA_cos_q25_t2,SAA_cos_q50_t2,SAA_cos_q75_t2,SAA_cos_q25_t3,SAA_cos_q50_t3,SAA_cos_q75_t3,SAA_cos_q25_t4,SAA_cos_q50_t4,SAA_cos_q75_t4,SAA_cos_q25_t5,SAA_cos_q50_t5,SAA_cos_q75_t5,SAA_cos_q25_t6,SAA_cos_q50_t6,SAA_cos_q75_t6,SAA_cos_q25_t7,SAA_cos_q50_t7,SAA_cos_q75_t7,SAA_cos_q1_mean_t0,SAA_cos_q1_mean_t1,SAA_cos_q1_mean_t2,SAA_cos_q1_mean_t3,SAA_cos_q1_mean_t4,SAA_cos_q1_mean_t5,SAA_cos_q1_mean_t6,SAA_cos_q1_mean_t7,SAA_cos_q2_mean_t0,SAA_cos_q2_mean_t1,SAA_cos_q2_mean_t2,SAA_cos_q2_mean_t3,SAA_cos_q2_mean_t4,SAA_cos_q2_mean_t5,SAA_cos_q2_mean_t6,SAA_cos_q2_mean_t7,SAA_cos_q3_mean_t0,SAA_cos_q3_mean_t1,SAA_cos_q3_mean_t2,SAA_cos_q3_mean_t3,SAA_cos_q3_mean_t4,SAA_cos_q3_mean_t5,SAA_cos_q3_mean_t6,SAA_cos_q3_mean_t7,SAA_cos_q4_mean_t0,SAA_cos_q4_mean_t1,SAA_cos_q4_mean_t2,SAA_cos_q4_mean_t3,SAA_cos_q4_mean_t4,SAA_cos_q4_mean_t5,SAA_cos_q4_mean_t6,SAA_cos_q4_mean_t7
0,-0.147072,0.246611,-1.681128,-0.010976,0.001575,0.264283,-2.080225,0.127459,0.103543,0.309742,-2.280185,0.233526,0.199936,0.294195,-2.119135,0.318208,0.039496,0.307913,0.347008,-0.095457,-0.073610,-0.055990,0.063944,0.078670,0.091392,0.180850,0.191738,0.202580,0.270456,0.279876,0.290221,-0.297348,-0.157087,-0.113018,-0.017534,-0.132270,0.025628,0.161101,0.256827,-0.119171,0.033429,0.147855,0.253059,-0.049193,0.094509,0.205815,0.295218,-1.891109,0.039605,-2.025005,-1.761102,-1.570820,0.042075,-1.710103,-1.412795,-1.255072,0.044353,-1.396612,-1.072579,-0.949160,0.046547,-1.091063,-0.745429,-0.656869,0.048738,-0.797764,-0.434164,-0.381215,0.050979,-0.520128,-0.141310,-0.124632,0.053284,-0.260679,0.132763,0.110851,0.055644,-0.021719,0.385159,-0.839753,0.661570,2.001959,-1.910684,-1.886632,-1.867925,-1.591477,-1.568910,-1.548792,-1.277169,-1.254973,-1.234113,-0.973179,-0.951132,-0.930049,-0.683295,-0.660950,-0.639274,-0.409964,-0.387397,-0.364904,...,-0.033545,1.564817,1.384645,1.175580,0.943301,0.693819,0.433516,0.168937,-0.093210,-1.914863,0.061407,-2.061364,-1.767261,-1.558604,0.060964,-1.704013,-1.412045,-1.219014,0.060444,-1.364599,-1.073603,-0.897528,0.059858,-1.041756,-0.753565,-0.595529,0.059235,-0.737052,-0.453388,-0.314318,0.058572,-0.453388,-0.174357,-0.055095,0.057900,-0.191974,0.080946,0.181030,0.057235,0.047570,0.314452,-0.796740,0.691618,2.095893,-1.959026,-1.915665,-1.870790,-1.602372,-1.559321,-1.514777,-1.262257,-1.219569,-1.175411,-0.940357,-0.898076,-0.854349,-0.638177,-0.596337,-0.553072,-0.357056,-0.314199,-0.271421,-0.098176,-0.055806,-0.012064,0.137419,0.180748,0.223981,-1.990818,-1.634355,-1.294304,-0.972103,-0.669156,-0.386749,-0.126091,0.111693,-1.907544,-1.554715,-1.218645,-0.900761,-0.602418,-0.324903,-0.069407,0.162976,-1.925487,-1.565775,-1.222637,-0.897497,-0.591789,-0.306803,-0.043779,0.196172,-1.841459,-1.485412,-1.146276,-0.825501,-0.524431,-0.244400,0.013424,0.247936
1,0.379524,0.443113,-2.468221,0.557758,0.425957,0.371649,-2.350228,0.579282,0.469748,0.306663,-2.151608,0.593129,0.506185,0.250055,-1.387287,0.604381,0.445353,0.353570,0.126661,0.512069,0.527519,0.538963,0.532943,0.550049,0.562340,0.546931,0.564816,0.577480,0.560037,0.576104,0.589263,-0.031920,0.083804,0.212461,0.319109,0.500166,0.530755,0.557038,0.571645,0.488633,0.506097,0.515401,0.532004,0.539012,0.564471,0.579793,0.591378,0.323522,0.058047,0.195045,0.613430,0.511954,0.060480,0.387312,0.816312,0.674947,0.062926,0.554562,0.992619,0.811516,0.065372,0.695830,1.141384,0.920856,0.067806,0.810151,1.261866,1.002344,0.070206,0.888022,1.353397,1.055524,0.072555,0.934345,1.415457,1.079810,0.074851,0.951938,1.447526,0.797559,0.264697,0.756288,0.290288,0.311593,0.337353,0.477952,0.498292,0.525759,0.640006,0.660494,0.690633,0.775186,0.796789,0.828709,0.882752,0.905913,0.938947,0.961440,0.987571,1.021199,...,-1.360923,-0.346175,-0.583389,-0.798514,-0.985669,-1.139714,-1.256224,-1.331890,-1.364501,0.393060,0.056582,0.262808,0.522402,0.580071,0.055981,0.454305,0.705461,0.741271,0.055439,0.619817,0.862894,0.875959,0.054936,0.758580,0.992616,0.983574,0.054537,0.871209,1.093920,1.063645,0.054226,0.956850,1.168737,1.115837,0.054023,1.015953,1.214779,1.139921,0.053925,1.046097,1.233691,0.861667,0.258709,0.746861,0.350232,0.393075,0.435815,0.536554,0.580355,0.624039,0.695656,0.741826,0.786467,0.830980,0.875364,0.920997,0.937556,0.982995,1.029663,1.017324,1.063879,1.110279,1.069345,1.115727,1.161951,1.093920,1.140218,1.186360,0.325618,0.514723,0.678202,0.815434,0.925732,1.008675,1.063887,1.091156,0.371275,0.554566,0.712088,0.843153,0.947194,1.023788,1.072604,1.093416,0.412039,0.602879,0.767901,0.906309,1.017627,1.101315,1.157039,1.184531,0.458112,0.643082,0.802037,0.934281,1.039289,1.116570,1.165822,1.186829
2,0.571499,0.162971,-1.642065,0.625779,0.575434,0.137374,-1.674577,0.621146,0.573271,0.124919,-1.777766,0.613629,0.570037,0.110067,-1.795198,0.602979,0.572560,0.135247,-0.001461,0.588006,0.599189,0.613591,0.585117,0.595808,0.609875,0.578944,0.589195,0.603107,0.569952,0.579693,0.593540,0.498432,0.525368,0.538911,0.553513,0.594100,0.590282,0.583480,0.574047,0.575025,0.572609,0.565089,0.557841,0.613932,0.610162,0.603090,0.593187,1.075073,0.077068,0.940729,1.449530,1.041623,0.079165,0.901088,1.421544,0.979655,0.081113,0.833312,1.363864,0.889520,0.082881,0.737772,1.276713,0.771734,0.084438,0.615063,1.160536,0.626983,0.085745,0.465926,1.015854,0.456132,0.086766,0.291253,0.843630,0.260238,0.087454,0.092231,0.644682,0.762620,0.286966,-0.814835,1.028548,1.063067,1.099961,0.993361,1.030181,1.068263,0.929371,0.968715,1.007688,0.837172,0.879188,0.919498,0.717729,0.761750,0.804138,0.571265,0.617513,0.662053,...,-0.274646,-1.353085,-1.297999,-1.200806,-1.064348,-0.892559,-0.690233,-0.462887,-0.216687,1.135793,0.053946,1.039252,1.230991,1.103473,0.054079,1.000857,1.203960,1.043095,0.054310,0.934797,1.149732,0.954923,0.054644,0.842089,1.067980,0.839333,0.055073,0.720856,0.956850,0.696867,0.055610,0.573298,0.819865,0.527993,0.056147,0.400205,0.654971,0.333571,0.056764,0.202376,0.464253,0.829381,0.275917,-0.802222,1.088463,1.136140,1.182295,1.057043,1.103465,1.149732,0.996737,1.043359,1.089828,0.908565,0.955473,1.000857,0.793431,0.839312,0.885055,0.652162,0.697057,0.741826,0.484131,0.528064,0.571885,0.290083,0.333066,0.375950,1.090335,1.061441,1.004606,0.920064,0.808182,0.669422,0.504417,0.313842,1.086139,1.050815,0.987579,0.896733,0.778621,0.633845,0.462831,0.266477,1.183714,1.154555,1.097202,1.011889,0.898982,0.759092,0.592446,0.400128,1.179490,1.143850,1.080034,0.988329,0.869155,0.723007,0.550474,0.352328
3,0.468371,0.121714,-1.786799,0.502949,0.428161,0.093946,-1.802266,0.462236,0.375203,0.078019,-1.752027,0.410369,0.309561,0.062843,-1.779299,0.345535,0.395324,0.109374,-0.158810,0.468813,0.476471,0.486970,0.426510,0.434045,0.443066,0.371701,0.380737,0.389221,0.302850,0.313507,0.323541,0.467429,0.426854,0.374478,0.309046,0.466443,0.421595,0.365239,0.293074,0.454484,0.424273,0.378045,0.323394,0.484450,0.439421,0.382720,0.312589,0.040574,0.087760,-0.129804,0.420050,-0.201339,0.087630,-0.373218,0.171290,-0.463691,0.086997,-0.636082,-0.100184,-0.744148,0.085785,-0.915871,-0.392296,-1.040165,0.083870,-1.209913,-0.702892,-1.348767,0.081030,-1.514644,-1.029820,-1.665794,0.076874,-1.825092,-1.370184,-1.985162,0.070716,-2.133610,-1.720422,-0.926061,0.672858,-2.025736,-0.020085,0.033809,0.083768,-0.263203,-0.207527,-0.155860,-0.525992,-0.469277,-0.416942,-0.806226,-0.749066,-0.695914,-1.101902,-1.044667,-0.990847,-1.409158,-1.352071,-1.298251,...,1.610618,0.041848,0.306104,0.569311,0.824814,1.066148,1.287147,1.481931,1.645029,0.114398,0.057428,-0.020806,0.248437,-0.128596,0.058094,-0.265526,0.008318,-0.394378,0.058760,-0.535189,-0.253742,-0.681796,0.059412,-0.824227,-0.539658,-0.989635,0.060032,-1.134348,-0.845308,-1.316578,0.060588,-1.461080,-1.170847,-1.661197,0.061098,-1.807412,-1.514777,-2.022046,0.061521,-2.168533,-1.875433,-0.884979,0.704801,-2.136445,0.072245,0.114270,0.157651,-0.171421,-0.128910,-0.086480,-0.437059,-0.394062,-0.351140,-0.725049,-0.681578,-0.639672,-1.032663,-0.990259,-0.946401,-1.360011,-1.317213,-1.272936,-1.705553,-1.660864,-1.617758,-2.067572,-2.022580,-1.977621,0.098508,-0.140641,-0.402584,-0.686238,-0.990341,-1.313607,-1.654670,-2.012044,0.045594,-0.198887,-0.465933,-0.754375,-1.063016,-1.390512,-1.735430,-2.096346,0.182832,-0.058492,-0.322851,-0.609057,-0.915953,-1.242198,-1.586333,-1.946970,0.129446,-0.117280,-0.386762,-0.677844,-0.989273,-1.319754,-1.667841,-2.032041
4,-0.794583,1.929876,-7.907318,-0.009575,-0.656066,1.924350,-8.582390,0.127016,-0.510223,1.783289,-8.578430,0.232658,-0.352589,1.609668,-8.569750,0.317833,-0.578365,1.823945,0.441993,-0.095268,-0.073075,-0.056342,0.062392,0.077838,0.090080,0.175387,0.185282,0.196391,0.264026,0.272644,0.283500,-2.729236,-2.627719,-2.379600,-2.052611,-0.406158,-0.255395,-0.136297,-0.006643,-0.102310,0.053072,0.169096,0.267181,-0.045019,0.099716,0.205384,0.290604,-1.885621,0.038456,-2.013944,-1.750487,-1.558003,0.041917,-1.692881,-1.396983,-1.233920,0.044812,-1.372931,-1.052684,-0.920713,0.047291,-1.061221,-0.721228,-0.622720,0.049547,-0.762354,-0.406401,-0.341601,0.051702,-0.479299,-0.110206,-0.079818,0.053799,-0.214876,0.165278,0.160575,0.055859,0.028835,0.419381,-0.810228,0.676083,2.046196,-1.905265,-1.879283,-1.866144,-1.578634,-1.554731,-1.541963,-1.255047,-1.233890,-1.218301,-0.943263,-0.925447,-0.904364,-0.647514,-0.631702,-0.606017,-0.369432,-0.353546,-0.323407,...,-0.037530,1.565770,1.385423,1.175991,0.943143,0.692915,0.431656,0.165948,-0.097495,-1.916964,0.061408,-2.062916,-1.770350,-1.559972,0.060963,-1.705553,-1.413577,-1.219613,0.060437,-1.364599,-1.073603,-0.897330,0.059860,-1.040240,-0.753565,-0.594504,0.059221,-0.735551,-0.451902,-0.312438,0.058569,-0.451902,-0.172890,-0.052334,0.057891,-0.189037,0.083847,0.184692,0.057223,0.050473,0.318749,-0.796058,0.693491,2.101656,-1.962126,-1.917214,-1.872338,-1.603911,-1.560858,-1.516313,-1.263782,-1.219569,-1.176933,-0.940357,-0.898076,-0.854349,-0.636681,-0.594843,-0.551580,-0.355577,-0.312723,-0.269947,-0.095252,-0.052888,-0.009152,0.141756,0.185075,0.226859,-1.992899,-1.635700,-1.294883,-0.971914,-0.668134,-0.384884,-0.123347,0.115331,-1.909478,-1.555906,-1.219071,-0.900375,-0.601209,-0.322846,-0.066481,0.166814,-1.927757,-1.567324,-1.223415,-0.897483,-0.590944,-0.305104,-0.041187,0.199659,-1.843577,-1.486796,-1.146888,-0.825299,-0.523404,-0.242502,0.016206,0.251619

In [13]:
# %% Conversion vers numpy pour modèles tabulaires

X_train_tab, X_val_tab, feature_columns = prepare_tabular_inputs(
    tabular_features_train,
    tabular_features_val,
)

y_train_flat = flatten_target(train_target)

print("X_train_tab :", X_train_tab.shape)
print("X_val_tab   :", X_val_tab.shape)
print("y_train_flat:", y_train_flat.shape)
print("Nombre de features tabulaires :", len(feature_columns))

X_train_tab : (25, 502)
X_val_tab   : (7, 502)
y_train_flat: (25, 10404)
Nombre de features tabulaires : 502

## 2. Métriques d'évaluation

Les modèles seront comparés avec :
- **RMSE** global,
- **MAE** global,
- **RMSE / MAE par horizon**,
- et **scores sur moyennes spatiales**.

Cette combinaison permet de distinguer :
- l'erreur globale sur le tenseur,
- la difficulté croissante selon l'horizon,
- et la capacité à prédire le niveau moyen d'irradiance indépendamment des détails spatiaux fins.

In [14]:
# %% Vérification rapide des métriques sur une prédiction nulle

dummy_pred = np.zeros_like(val_target)

print("Scores globaux - prédiction nulle")
display(evaluate_forecasts(val_target, dummy_pred))

print("Scores par horizon - prédiction nulle")
display(evaluate_by_horizon(val_target, dummy_pred))

print("Scores sur moyenne spatiale - prédiction nulle")
display(evaluate_spatial_means(val_target, dummy_pred))

Scores globaux - prédiction nulle

  metric       value
0   RMSE  392.485415
1    MAE  367.200385
2     R2   -7.019542
3   MAPE  100.000000

Scores par horizon - prédiction nulle

   horizon_min        RMSE         MAE
0           15  398.994495  380.848920
1           30  395.346910  373.443357
2           45  390.693096  363.697722
3           60  384.762683  350.811542

Scores sur moyenne spatiale - prédiction nulle

   horizon_min  RMSE_spatial_mean  MAE_spatial_mean
0           15         397.920569        380.848920
1           30         394.299381        373.443357
2           45         389.692109        363.697722
3           60         383.795096        350.811542

## 3. Baseline 1 — persistance brute

Première baseline : on suppose que les futures images ressemblent à la dernière image observée de `GHI`.

Formellement :

$$
\hat{Y}_{t+h} = GHI_t
$$

pour chacun des horizons futurs.

In [15]:
# %% Baseline persistance brute

y_pred_persistence_raw = persistence_last_ghi_baseline(val_arrays_raw)

print("Shape y_pred_persistence_raw :", y_pred_persistence_raw.shape)

baseline_raw_results = evaluate_model_bundle(
    val_target,
    y_pred_persistence_raw,
    model_name="persistence_raw",
)

print("Scores globaux")
display(baseline_raw_results["global"])

print("Scores par horizon")
display(baseline_raw_results["by_horizon"])

print("Scores sur moyenne spatiale")
display(baseline_raw_results["spatial_means"])

Shape y_pred_persistence_raw : (7, 4, 51, 51)
Scores globaux

  metric      value            model
0   RMSE  77.652985  persistence_raw
1    MAE  63.439056  persistence_raw
2     R2   0.686080  persistence_raw
3   MAPE  27.925336  persistence_raw

Scores par horizon

   horizon_min        RMSE         MAE            model
0           15   28.998959   25.867481  persistence_raw
1           30   57.192327   51.134476  persistence_raw
2           45   84.976879   75.965643  persistence_raw
3           60  113.079497  100.788624  persistence_raw

Scores sur moyenne spatiale

   horizon_min  RMSE_spatial_mean  MAE_spatial_mean            model
0           15          27.887018         25.339949  persistence_raw
1           30          55.861563         50.583423  persistence_raw
2           45          83.284027         75.247970  persistence_raw
3           60         111.344196         99.886624  persistence_raw

In [16]:
# %% Baseline persistance brute

y_pred_persistence_raw = persistence_last_ghi_baseline(val_arrays_raw)

print("Shape y_pred_persistence_raw :", y_pred_persistence_raw.shape)

baseline_raw_results = evaluate_model_bundle(
    val_target,
    y_pred_persistence_raw,
    model_name="persistence_raw",
)

print("Scores globaux")
display(baseline_raw_results["global"])

print("Scores par horizon")
display(baseline_raw_results["by_horizon"])

print("Scores sur moyenne spatiale")
display(baseline_raw_results["spatial_means"])

Shape y_pred_persistence_raw : (7, 4, 51, 51)
Scores globaux

  metric      value            model
0   RMSE  77.652985  persistence_raw
1    MAE  63.439056  persistence_raw
2     R2   0.686080  persistence_raw
3   MAPE  27.925336  persistence_raw

Scores par horizon

   horizon_min        RMSE         MAE            model
0           15   28.998959   25.867481  persistence_raw
1           30   57.192327   51.134476  persistence_raw
2           45   84.976879   75.965643  persistence_raw
3           60  113.079497  100.788624  persistence_raw

Scores sur moyenne spatiale

   horizon_min  RMSE_spatial_mean  MAE_spatial_mean            model
0           15          27.887018         25.339949  persistence_raw
1           30          55.861563         50.583423  persistence_raw
2           45          83.284027         75.247970  persistence_raw
3           60         111.344196         99.886624  persistence_raw

In [18]:
baseline_raw_results

{'global':   metric      value            model
 0   RMSE  77.652985  persistence_raw
 1    MAE  63.439056  persistence_raw
 2     R2   0.686080  persistence_raw
 3   MAPE  27.925336  persistence_raw,
 'by_horizon':    horizon_min        RMSE         MAE            model
 0           15   28.998959   25.867481  persistence_raw
 1           30   57.192327   51.134476  persistence_raw
 2           45   84.976879   75.965643  persistence_raw
 3           60  113.079497  100.788624  persistence_raw,
 'spatial_means':    horizon_min  RMSE_spatial_mean  MAE_spatial_mean            model
 0           15          27.887018         25.339949  persistence_raw
 1           30          55.861563         50.583423  persistence_raw
 2           45          83.284027         75.247970  persistence_raw
 3           60         111.344196         99.886624  persistence_raw}

In [17]:
# 1. On récupère le RMSE de la persistence CSI (ton champion actuel)
persistence_rmse = baseline_raw_results["persistence_csi"]["global"].query("metric == 'RMSE'")["value"].values[0]

# 2. On entraîne un modèle avec les nouvelles features
from sklearn.ensemble import RandomForestRegressor
model_adv = RandomForestRegressor(n_estimators=100, random_state=42)
model_adv.fit(X_train_adv, y_train_flat)

# 3. Évaluation
y_pred_adv = model_adv.predict(X_val_adv).reshape(val_target.shape)
res_adv = evaluate_model_bundle(val_target, y_pred_adv, model_name="RF_Advanced_Features")

# 4. Ajout des Skill Scores au tableau comparatif
import pandas as pd
all_results_df = pd.concat([bundle["global"] for bundle in baseline_raw_results.values()])
all_results_df = add_skill_scores(all_results_df, persistence_rmse)

display(all_results_df.sort_values("skill_score", ascending=False))

KeyError: 'persistence_csi'

## 4. Baseline 2 — persistance du clear-sky index

Deuxième baseline, plus cohérente avec la physique du problème :

- on suppose que le `CSI` reste constant à court terme ;
- on reconstruit ensuite `GHI` futur à partir du `CLS` futur.

$$
\widehat{CSI}_{t+h} = CSI_t
$$

puis

$$
\widehat{GHI}_{t+h} = \widehat{CSI}_{t+h} \times CLS_{t+h}
$$

In [ ]:
# %% Baseline persistance CSI

y_pred_persistence_csi = persistence_csi_baseline(val_arrays_raw)

print("Shape y_pred_persistence_csi :", y_pred_persistence_csi.shape)

baseline_csi_results = evaluate_model_bundle(
    val_target,
    y_pred_persistence_csi,
    model_name="persistence_csi",
)

print("Scores globaux")
display(baseline_csi_results["global"])

print("Scores par horizon")
display(baseline_csi_results["by_horizon"])

print("Scores sur moyenne spatiale")
display(baseline_csi_results["spatial_means"])

Shape y_pred_persistence_csi : (7, 4, 51, 51)
Scores globaux

  metric      value            model
0   RMSE  13.692846  persistence_csi
1    MAE   7.372206  persistence_csi

Scores par horizon

   horizon_min       RMSE        MAE            model
0           15   7.704670   4.140720  persistence_csi
1           30  11.665896   6.456973  persistence_csi
2           45  15.359845   8.693140  persistence_csi
3           60  17.849264  10.197991  persistence_csi

Scores sur moyenne spatiale

   horizon_min  RMSE_spatial_mean  MAE_spatial_mean            model
0           15           1.543409          1.294094  persistence_csi
1           30           2.888295          2.305033  persistence_csi
2           45           3.735279          2.803421  persistence_csi
3           60           4.933677          3.717848  persistence_csi

## 5. Baseline 3 — image moyenne du train

Cette baseline est volontairement très faible :
on prédit pour chaque exemple de validation la moyenne des cibles du train.

Elle sert surtout de borne basse de référence.

In [ ]:
# %% Baseline image moyenne

y_pred_mean = mean_image_baseline(train_target, n_samples=len(val_target))

baseline_mean_results = evaluate_model_bundle(
    val_target,
    y_pred_mean,
    model_name="mean_image",
)

print("Scores globaux")
display(baseline_mean_results["global"])

print("Scores par horizon")
display(baseline_mean_results["by_horizon"])

Scores globaux

  metric       value       model
0   RMSE  138.899038  mean_image
1    MAE  125.968348  mean_image

Scores par horizon

   horizon_min        RMSE         MAE       model
0           15  121.229709  117.251295  mean_image
1           30  130.792706  122.209406  mean_image
2           45  142.953652  126.661947  mean_image
3           60  157.900759  137.750746  mean_image

## 6. Comparaison initiale des baselines

On compare maintenant les trois baselines pour identifier la référence la plus difficile à battre.

In [ ]:
# %% Comparaison globale des baselines

baseline_results = {
    "persistence_raw": baseline_raw_results,
    "persistence_csi": baseline_csi_results,
    "mean_image": baseline_mean_results,
}

display(compare_global_scores(baseline_results))

             model        RMSE         MAE
0  persistence_csi   13.692846    7.372206
1  persistence_raw   77.652985   63.439056
2       mean_image  138.899038  125.968348

In [ ]:
# %% Comparaison par horizon

baseline_horizon_comparison = pd.concat(
    [
        baseline_raw_results["by_horizon"],
        baseline_csi_results["by_horizon"],
        baseline_mean_results["by_horizon"],
    ],
    ignore_index=True,
)

display(baseline_horizon_comparison)

    horizon_min        RMSE         MAE            model
0            15   28.998959   25.867481  persistence_raw
1            30   57.192327   51.134476  persistence_raw
2            45   84.976879   75.965643  persistence_raw
3            60  113.079497  100.788624  persistence_raw
4            15    7.704670    4.140720  persistence_csi
5            30   11.665896    6.456973  persistence_csi
6            45   15.359845    8.693140  persistence_csi
7            60   17.849264   10.197991  persistence_csi
8            15  121.229709  117.251295       mean_image
9            30  130.792706  122.209406       mean_image
10           45  142.953652  126.661947       mean_image
11           60  157.900759  137.750746       mean_image

## 7. Modèle 1 — Ridge Regression

Ridge est un premier modèle linéaire régularisé.

Il est particulièrement utile ici car :
- les features tabulaires sont nombreuses ;
- elles sont potentiellement corrélées ;
- la régularisation L2 améliore la stabilité de l'estimation.

In [ ]:
# %% Ridge

ridge_model = fit_ridge_multioutput(
    X_train_tab,
    y_train_flat,
    alpha=RIDGE_ALPHA,
    random_state=RANDOM_STATE,
)

y_pred_ridge = predict_tensor(ridge_model, X_val_tab)

ridge_results = evaluate_model_bundle(
    val_target,
    y_pred_ridge,
    model_name="ridge",
)

print("Scores globaux")
display(ridge_results["global"])

print("Scores par horizon")
display(ridge_results["by_horizon"])

Scores globaux

  metric      value  model
0   RMSE  31.092976  ridge
1    MAE  16.607825  ridge

Scores par horizon

   horizon_min       RMSE        MAE  model
0           15  30.383527  16.298581  ridge
1           30  30.990332  16.704750  ridge
2           45  31.285059  16.610637  ridge
3           60  31.698238  16.817330  ridge

In [ ]:
import gc
# Après avoir fini Ridge et stocké les scores
del ridge_model 
gc.collect()

## 8. Modèle 2 — Elastic Net

Elastic Net combine :
- la régularisation L1 (sélection partielle de variables),
- et la régularisation L2 (stabilité).

Il peut être utile lorsque les features sont nombreuses et partiellement redondantes.

In [ ]:
# %% Elastic Net

elasticnet_model = fit_elasticnet_multioutput(
    X_train_tab,
    y_train_flat,
    alpha=ELASTICNET_ALPHA,
    l1_ratio=ELASTICNET_L1_RATIO,
    random_state=RANDOM_STATE,
)

y_pred_elasticnet = predict_tensor(elasticnet_model, X_val_tab)

elasticnet_results = evaluate_model_bundle(
    val_target,
    y_pred_elasticnet,
    model_name="elasticnet",
)

print("Scores globaux")
display(elasticnet_results["global"])

print("Scores par horizon")
display(elasticnet_results["by_horizon"])

Scores globaux

  metric      value       model
0   RMSE  39.307231  elasticnet
1    MAE  22.815631  elasticnet

Scores par horizon

   horizon_min       RMSE        MAE       model
0           15  39.164402  22.886419  elasticnet
1           30  39.706616  23.412016  elasticnet
2           45  39.095447  22.681745  elasticnet
3           60  39.259573  22.282345  elasticnet

## 9. Modèle 3 — Random Forest

Random Forest est un premier modèle non linéaire capable de capturer :
- des interactions entre variables ;
- des effets non linéaires ;
- tout en restant relativement robuste.

In [ ]:
# %% Random Forest

rf_model = fit_random_forest_multioutput(
    X_train_tab,
    y_train_flat,
    n_estimators=RF_N_ESTIMATORS,
    max_depth=RF_MAX_DEPTH,
    random_state=RANDOM_STATE,
)

y_pred_rf = predict_tensor(rf_model, X_val_tab)

rf_results = evaluate_model_bundle(
    val_target,
    y_pred_rf,
    model_name="random_forest",
)

print("Scores globaux")
display(rf_results["global"])

print("Scores par horizon")
display(rf_results["by_horizon"])

Scores globaux

  metric      value          model
0   RMSE  35.258683  random_forest
1    MAE  24.232948  random_forest

Scores par horizon

   horizon_min       RMSE        MAE          model
0           15  35.811201  24.973871  random_forest
1           30  35.566459  24.714165  random_forest
2           45  34.913329  23.903556  random_forest
3           60  34.732452  23.340200  random_forest

## 10. Modèle 4 — HistGradientBoosting

HistGradientBoosting est un modèle de boosting tabulaire souvent très performant,
notamment lorsqu'il existe des effets non linéaires complexes.

Dans cette première version, on l'utilise avec des hyperparamètres simples, sans tuning approfondi.

In [ ]:
# %% HistGradientBoosting

hgb_model = fit_hist_gb_multioutput(
    X_train_tab,
    y_train_flat,
    max_depth=HGB_MAX_DEPTH,
    learning_rate=HGB_LEARNING_RATE,
    max_iter=HGB_MAX_ITER,
    random_state=RANDOM_STATE,
)

y_pred_hgb = predict_tensor(hgb_model, X_val_tab)

hgb_results = evaluate_model_bundle(
    val_target,
    y_pred_hgb,
    model_name="hist_gradient_boosting",
)

print("Scores globaux")
display(hgb_results["global"])

print("Scores par horizon")
display(hgb_results["by_horizon"])

KeyboardInterrupt:

## 11. Comparaison finale des modèles

On agrège maintenant les performances de toutes les baselines et de tous les modèles testés
pour comparer proprement les résultats.

In [ ]:
# %% Comparaison globale

all_results = {
    "persistence_raw": baseline_raw_results,
    "persistence_csi": baseline_csi_results,
    "mean_image": baseline_mean_results,
    "ridge": ridge_results,
    "elasticnet": elasticnet_results,
    "random_forest": rf_results,
    "hist_gradient_boosting": hgb_results,
}

global_comparison = compare_global_scores(all_results)
display(global_comparison)

NameError: name 'hgb_results' is not defined

In [ ]:
# %% Comparaison par horizon

horizon_comparison = pd.concat(
    [bundle["by_horizon"] for bundle in all_results.values()],
    ignore_index=True,
)

display(horizon_comparison)

In [ ]:
# %% Comparaison sur moyenne spatiale

spatial_mean_comparison = pd.concat(
    [bundle["spatial_means"] for bundle in all_results.values()],
    ignore_index=True,
)

display(spatial_mean_comparison)

## 12. Visualisation synthétique

On visualise ici les scores par horizon pour comparer la dégradation des performances
lorsque l'horizon de prévision augmente.

In [ ]:
# %% Courbe RMSE par horizon

fig, ax = plt.subplots(figsize=(8, 5))

for model_name, bundle in all_results.items():
    df = bundle["by_horizon"]
    ax.plot(df["horizon_min"], df["RMSE"], marker="o", label=model_name)

ax.set_xlabel("Horizon (minutes)")
ax.set_ylabel("RMSE")
ax.set_title("Comparaison des modèles par horizon - RMSE")
ax.legend()
plt.show()

In [ ]:
# %% Courbe MAE par horizon

fig, ax = plt.subplots(figsize=(8, 5))

for model_name, bundle in all_results.items():
    df = bundle["by_horizon"]
    ax.plot(df["horizon_min"], df["MAE"], marker="o", label=model_name)

ax.set_xlabel("Horizon (minutes)")
ax.set_ylabel("MAE")
ax.set_title("Comparaison des modèles par horizon - MAE")
ax.legend()
plt.show()

In [ ]:
# Comparaison visuelle pour le meilleur modèle
print("Analyse du modèle RF avec Features Avancées :")
plot_error_analysis(val_target, y_pred_adv, title="Random Forest : Réel vs Prédit")

## 13. Conclusion

Ce notebook a permis :

- de définir les métriques de comparaison ;
- d'établir plusieurs baselines de référence ;
- d'entraîner plusieurs modèles tabulaires supervisés ;
- de comparer leurs performances globales et par horizon.

### Points à retenir
- la baseline la plus forte donne la vraie référence à battre ;
- les modèles linéaires régularisés permettent de tester rapidement la valeur des features tabulaires ;
- les modèles non linéaires (Random Forest, boosting) permettent de capturer des interactions plus complexes.

### Suite logique
Le notebook suivant pourra approfondir :
- le tuning des hyperparamètres ;
- une validation temporelle plus robuste ;
- l'analyse des variables importantes ;
- et éventuellement une extension vers des modèles plus riches.